### ISSUE TITLE
Feature request: add back Lua 5.1 support

### ISSUE THREAD

**Issue by hishamhm** [ntd/luasyslog#1]
Please consider adding back Lua 5.1 support. You can use the helper files from [lua-compat-5.2](https://github.com/keplerproject/lua-compat-5.2) here for minimal impact on the codebase.

(Also, the `luasyslog` entry in https://luarocks.org is unmaintained (it's stil owned by the `luarocks` fallback account since the luarocks.org migration years ago) -- if you add back Lua 5.1 support we can put your fork in the root manifest as the default one, since other rocks depending on root `luasyslog` expect Lua 5.1 support.

Thank you!

**Comment by hishamhm** [comment]
I made a PR with the lua-compat-5.2 addition, hope that helps! :)

**Comment by ntd** [comment]
I just released 2.2.0 that includes this feature request.
